#!/bin/bash
# This script will copy openshift_settings to quokka/local_settings
# after the first deploy, make your settings changes only on quokka/local_settings.py
cd $OPENSHIFT_REPO_DIR
cp etc/openshift_settings.py quokka/local_settings.py

#rm -rf ${OPENSHIFT_PYTHON_DIR}virtenv
#cd ${OPENSHIFT_PYTHON_DIR}
#virtualenv virtenv

source ${OPENSHIFT_PYTHON_DIR}virtenv/bin/activate
#export PYTHON_EGG_CACHE=${OPENSHIFT_PYTHON_DIR}virtenv/lib/python-2.7/site-packages

cd $OPENSHIFT_REPO_DIR
export PYTHONPATH=$PWD

echo "installing requirements"
pip install -r requirements/requirements.txt --upgrade

echo "installing test requirements"
pip install -r requirements/dev.txt --upgrade
