#!/bin/bash
# This script will copy openshift_settings to quokka/local_settings
# after the first deploy, make your settings changes only on quokka/local_settings.py
cd $OPENSHIFT_REPO_DIR
cp etc/openshift_settings.py quokka/local_settings.py