#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.
$OPENSHIFT_PYTHON_DIR/virtenv/bin/python etc/openshift_clean.py