#!/bin/bash
# This script runs only for quokka cms official demo page
if [ "$OPENSHIFT_NAMESPACE" == "rochacbruno" ]; then
   source ${OPENSHIFT_PYTHON_DIR}virtenv/bin/activate
   export PYTHON_EGG_CACHE=${OPENSHIFT_PYTHON_DIR}virtenv/lib/python-2.7/site-packages

   cd $OPENSHIFT_REPO_DIR
   export PYTHONPATH=$PWD

   echo "c603c78bbeba8d9" > quokka/static/vaddy-c603c78bbeba8d9.html

   echo "Executing 'python ${OPENSHIFT_REPO_DIR}etc/openshift_clean.py'"
   python "$OPENSHIFT_REPO_DIR"etc/openshift_clean.py

   echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py populate -f ./etc/fixtures/demo_data.json'"
   python "$OPENSHIFT_REPO_DIR"manage.py populate -f ./etc/fixtures/demo_data.json -b http://"$OPENSHIFT_GEAR_DNS"
fi
